### ISSUE TITLE
Check list message performance (response time)

### ISSUE THREAD

**Issue by weeco** [kafka-owl/kafka-owl#6]
When listing messages Kafka Owl has to do a couple of requests sequentially. It fetches the partitionIDs for the requested topics, the low & high watermarks, starts a partition consumer for each partition etc. I have seen response times which **take up to 4.3s** for a topic with 50 partitions (regardless of the message size).

Therefore we should make sure that as many requests as possible will be run concurrently (or can be periodically prefetched so that we can potentially save a request upon invocation).

- [x] Fetch watermarks concurrently
- [x] Check what requests could be periodically prefetched so that they do not need to be fetched upon invocation (this is now tracked under https://github.com/kafka-owl/kafka-owl/issues/20)

**Comment by rikimaru0345** [comment]
We probably need to build a very simple benchmark tool to get reliable and reproducible timings.
Otherwise there is no way to track regressions here.

Ideally the performance tests are implemented as / combined with the unit tests.

I suggest including tests for cold-starts as well. (Kafka owl should pre warm itself while starting to do well here)
